# Generated by Django 2.2.5 on 2019-12-13 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20191211_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentjoin',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 12, 13)),
        ),
        migrations.AlterField(
            model_name='tournamentjoin',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 12, 13)),
        ),
    ]
